development:
  adapter: postgresql
  host: localhost
  database: reservation
  username: test
  password: test
  encoding: utf8
  
test:
  adapter: postgresql
  host: localhost
  database: reservation_test
  username: test
  password: test
  encoding: utf8
